---
abstract: 'Cover-My-Ass-Mode script'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CMAM
no_index:
  directory:
    - inc
    - t
requires:
  Mac::FSEvents: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
